apiVersion: v1
kind: ConfigMap
metadata:
  name: simulator-conf
data:
  env: |
    KafkaReadTopic=route.new-direction
    KafkaProduceTopic=route.new-position
    KafkaBootstrapServers=pkc-lzvrd.us-west4.gcp.confluent.cloud:9092
    KafkaConsumerGroupId=simulator
    security.protocol="SASL_SSL"
    sasl.mechanisms="PLAIN"
    sasl.username="RZQYZQ2AGQKECEGX"
    sasl.password="ZSguRZzyse8jz2mpCuZRQSfel9bFMW62IWVErnj/jv9S8edZBU1KJ6x/yru7oHY/"